/**
 * This package's contents are generated by Orval from the FastAPI OpenAPI
 * schema (see `orval.config.ts`). Nothing here should be hand-written once
 * generation is wired up — this placeholder exists only until the API exists.
 */
export {};
